name: build

on:
  push:
    branches:
    - develop
    - master

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Start containers
      run: docker-compose up --detach --build
    - name: Open Docker container's shell
      run: docker exec -it epam-lab_web_1 bash
    - name: Run tests
      run: python manage.py test
    - name: Close Docker container's shell
      run: exit     
    - name: Stop containers
      if: always()
      run: docker-compose down
