name: build

on:
  push:
    branches:
    - develop
    - master

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Start containers
      run: docker-compose up --detach --build
    - name: Install Dependencies
      run: | 
        docker exec epam-lab_web_1 python -m pip install --upgrade pip
        docker exec epam-lab_web_1 pip install coveralls pylint-django
    - name: Analysing the code with pylint
      run: docker exec epam-lab_web_1 pylint */*
    - name: Run tests
      run: docker exec epam-lab_web_1 coverage run manage.py test
    - name: Coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: docker exec -e COVERALLS_REPO_TOKEN="$GITHUB_TOKEN" epam-lab_web_1 coveralls --service=github
    - name: Stop containers
      if: always()
      run: docker-compose down
